cd ..
./gradlew :app:testDevelopDebugUnitTest
./gradlew :core:testDevelopDebugUnitTest
./gradlew :core:ui_components:testDevelopDebugUnitTest
./gradlew :data:profile:testDevelopDebugUnitTest
./gradlew :data:web_sockets:testDevelopDebugUnitTest
./gradlew :data:food:testDevelopDebugUnitTest
./gradlew :data:favorite:testDevelopDebugUnitTest
./gradlew :domain:user_profile:testDevelopDebugUnitTest
./gradlew :domain:web_sockets:testDevelopDebugUnitTest
./gradlew :features:authentication:testDevelopDebugUnitTest
./gradlew :features:connectivity:testDevelopDebugUnitTest
./gradlew :features:food_detail:testDevelopDebugUnitTest
./gradlew :features:main:testDevelopDebugUnitTest
./gradlew :features:search_food:testDevelopDebugUnitTest
./gradlew :features:splash_screen:testDevelopDebugUnitTest
./gradlew :features:user_profile:testDevelopDebugUnitTest
./gradlew :features:welcome:testDevelopDebugUnitTest
